name: 🚀 Production Deploy

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        ref: main

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 SFTP Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      with:
        server: ${{ secrets.PROD_FTP_HOST }}
        username: ${{ secrets.PROD_FTP_USER }}
        sftp_only: true
        password: ${{ secrets.PROD_FTP_PASSWORD }}
        port: 22
        rsyncArgs: --exclude=**/.git/ --exclude=**/node_modules/ --exclude=**/src/images/
