name: 🚀 Production Deploy

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        ref: main

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 🚀 FTP/SFTP file deployer
      uses: milanmk/actions-file-deployer@1.17
      with:
        remote-protocol: "sftp"
        remote-host: ${{ secrets.PROD_FTP_HOST }}
        remote-user: ${{ secrets.PROD_FTP_USER }}
        remote-password: ${{ secrets.PROD_FTP_PASSWORD }}
        sync: "full"
        sync-delta-excludes: "**/.git/,**/node_modules/,**/src/images/"
